// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCursos.Data;

#nullable disable

namespace SistemaCursos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaCursos.Models.CursoModel", b =>
                {
                    b.Property<int>("curso_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("curso_id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.HasKey("curso_id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("SistemaCursos.Models.EstudianteModel", b =>
                {
                    b.Property<int>("estudiante_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("estudiante_id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.HasKey("estudiante_id");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("SistemaCursos.Models.InscripcionModel", b =>
                {
                    b.Property<int>("inscripcion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("inscripcion_id"));

                    b.Property<int>("curso_id")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("estudiante_id")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("fecha_inscripcion")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.HasKey("inscripcion_id");

                    b.HasIndex("curso_id");

                    b.HasIndex("estudiante_id");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("SistemaCursos.Models.InscripcionModel", b =>
                {
                    b.HasOne("SistemaCursos.Models.CursoModel", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("curso_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCursos.Models.EstudianteModel", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("estudiante_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("SistemaCursos.Models.CursoModel", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("SistemaCursos.Models.EstudianteModel", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
